package powerdns

import (
	"strings"
	"testing"

	operatorconfig "github.com/astradns/astradns-operator/pkg/engineconfig"
	v1alpha1 "github.com/astradns/astradns-types/api/v1alpha1"
	"github.com/astradns/astradns-types/engine"
)

func TestPowerDNSRendererRenderFullConfig(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	config := &engine.EngineConfig{
		Upstreams: []engine.UpstreamConfig{
			{Address: "1.1.1.1", Port: 53},
			{Address: "8.8.8.8", Port: 5353},
		},
		Cache: engine.CacheConfig{
			MaxEntries:        4096,
			PositiveTtlMin:    30,
			PositiveTtlMax:    120,
			NegativeTtl:       20,
			PrefetchEnabled:   true,
			PrefetchThreshold: 7,
		},
		ListenAddr:    "0.0.0.0",
		ListenPort:    5354,
		WorkerThreads: 2,
		DNSSEC:        engine.DNSSECConfig{Mode: engine.DNSSECModeOff},
	}

	got, err := renderer.Render(config)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	expected := `# PowerDNS Recursor configuration — generated by AstraDNS
local-address=0.0.0.0
local-port=5354
daemon=no
write-pid=no
disable-syslog=yes
log-common-errors=yes
threads=2
max-cache-entries=4096
max-negative-ttl=20
minimum-ttl-override=30
max-cache-ttl=120
dnssec=off
forward-zones=.=1.1.1.1:53;8.8.8.8:5353
allow-from=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16`

	if strings.TrimSpace(got) != strings.TrimSpace(expected) {
		t.Fatalf("Render() output mismatch\nexpected:\n%s\n\ngot:\n%s", expected, got)
	}
}

func TestPowerDNSRendererRenderDefaults(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	config := &engine.EngineConfig{
		Upstreams: []engine.UpstreamConfig{{Address: "1.1.1.1", Port: 53}},
		Cache: engine.CacheConfig{
			MaxEntries:     100000,
			PositiveTtlMin: 60,
			PositiveTtlMax: 300,
			NegativeTtl:    30,
		},
		ListenAddr:    "127.0.0.1",
		ListenPort:    5354,
		WorkerThreads: 2,
	}

	got, err := renderer.Render(config)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	checks := []string{
		"local-address=127.0.0.1",
		"local-port=5354",
		"max-cache-entries=100000",
		"dnssec=off",
		"forward-zones=.=1.1.1.1:53",
	}

	for _, check := range checks {
		if !strings.Contains(got, check) {
			t.Fatalf("Render() output does not contain %q\nfull output:\n%s", check, got)
		}
	}
}

func TestPowerDNSRendererRoundTrip(t *testing.T) {
	t.Parallel()

	gen := &operatorconfig.DefaultConfigGenerator{}
	pool := &v1alpha1.DNSUpstreamPool{
		Spec: v1alpha1.DNSUpstreamPoolSpec{
			Runtime: v1alpha1.RuntimeConfig{WorkerThreads: 2},
			Upstreams: []v1alpha1.Upstream{
				{Address: "1.1.1.1"},
				{Address: "8.8.8.8", Port: 5353},
			},
		},
	}
	profile := &v1alpha1.DNSCacheProfile{
		Spec: v1alpha1.DNSCacheProfileSpec{
			MaxEntries: 2048,
			PositiveTtl: v1alpha1.TtlConfig{
				MinSeconds: 45,
				MaxSeconds: 180,
			},
			NegativeTtl: v1alpha1.NegTtlConfig{Seconds: 20},
			Prefetch:    v1alpha1.PrefetchConfig{Enabled: true, Threshold: 8},
		},
	}

	config, err := gen.Generate(pool, profile)
	if err != nil {
		t.Fatalf("Generate() returned error: %v", err)
	}

	renderer := &PowerDNSRenderer{}
	got, err := renderer.Render(config)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	expected := `# PowerDNS Recursor configuration — generated by AstraDNS
local-address=127.0.0.1
local-port=5354
daemon=no
write-pid=no
disable-syslog=yes
log-common-errors=yes
threads=2
max-cache-entries=2048
max-negative-ttl=20
minimum-ttl-override=45
max-cache-ttl=180
dnssec=off
forward-zones=.=1.1.1.1:53;8.8.8.8:5353
allow-from=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16`

	if strings.TrimSpace(got) != strings.TrimSpace(expected) {
		t.Fatalf("round-trip output mismatch\nexpected:\n%s\n\ngot:\n%s", expected, got)
	}
}

func TestPowerDNSRendererMetadata(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	if renderer.EngineType() != engine.EnginePowerDNS {
		t.Fatalf("EngineType() = %q, want %q", renderer.EngineType(), engine.EnginePowerDNS)
	}
	if renderer.ConfigFileName() != "recursor.conf" {
		t.Fatalf("ConfigFileName() = %q, want %q", renderer.ConfigFileName(), "recursor.conf")
	}
}

// validPowerDNSConfig returns a minimal valid EngineConfig for PowerDNS rendering tests.
// Callers should override only the fields relevant to their test scenario.
func validPowerDNSConfig() *engine.EngineConfig {
	return &engine.EngineConfig{
		Upstreams: []engine.UpstreamConfig{
			{Address: "1.1.1.1", Port: 53},
		},
		Cache: engine.CacheConfig{
			MaxEntries:     100000,
			PositiveTtlMin: 60,
			PositiveTtlMax: 300,
			NegativeTtl:    30,
		},
		ListenAddr:    "127.0.0.1",
		ListenPort:    5354,
		WorkerThreads: 2,
		DNSSEC:        engine.DNSSECConfig{Mode: engine.DNSSECModeOff},
	}
}

// --- Gap 9: IPv6 upstream addresses in rendering ---

func TestPowerDNSRendererIPv6Upstreams(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		upstreams []engine.UpstreamConfig
		checks    []string
	}{
		{
			name: "single IPv6 loopback with port 53",
			upstreams: []engine.UpstreamConfig{
				{Address: "::1", Port: 53},
			},
			checks: []string{
				"forward-zones=.=::1:53",
			},
		},
		{
			name: "IPv6 upstream with non-standard port 5353",
			upstreams: []engine.UpstreamConfig{
				{Address: "2001:db8::1", Port: 5353},
			},
			checks: []string{
				"forward-zones=.=2001:db8::1:5353",
			},
		},
		{
			name: "mixed IPv4 and IPv6 upstreams",
			upstreams: []engine.UpstreamConfig{
				{Address: "1.1.1.1", Port: 53},
				{Address: "2001:db8::1", Port: 5353},
			},
			checks: []string{
				"forward-zones=.=1.1.1.1:53;2001:db8::1:5353",
			},
		},
	}

	renderer := &PowerDNSRenderer{}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			config := validPowerDNSConfig()
			config.Upstreams = tt.upstreams

			got, err := renderer.Render(config)
			if err != nil {
				t.Fatalf("Render() returned error: %v", err)
			}

			for _, check := range tt.checks {
				if !strings.Contains(got, check) {
					t.Fatalf("Render() output does not contain %q\nfull output:\n%s", check, got)
				}
			}
		})
	}
}

// --- Gap 12: Empty upstreams list in rendering ---

func TestPowerDNSRendererEmptyUpstreams(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	config := validPowerDNSConfig()
	config.Upstreams = []engine.UpstreamConfig{}

	got, err := renderer.Render(config)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	// With no upstreams, forward-zones should render with an empty address list.
	if !strings.Contains(got, "forward-zones=.=") {
		t.Fatalf("Render() output should contain forward-zones directive\nfull output:\n%s", got)
	}
}

func TestPowerDNSRendererUpstreamPortZeroNormalization(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	config := validPowerDNSConfig()
	config.Upstreams = []engine.UpstreamConfig{
		{Address: "9.9.9.9", Port: 0},
	}

	got, err := renderer.Render(config)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	if !strings.Contains(got, "forward-zones=.=9.9.9.9:53") {
		t.Fatalf("Render() output should normalize port 0 to 53\nfull output:\n%s", got)
	}
	if strings.Contains(got, "9.9.9.9:0") {
		t.Fatalf("Render() output should not contain port 0\nfull output:\n%s", got)
	}
}

// --- Gap 14: Zero/negative cache values in rendering ---

func TestPowerDNSRendererZeroCacheValues(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		cache  engine.CacheConfig
		checks []string
	}{
		{
			name: "MaxEntries zero",
			cache: engine.CacheConfig{
				MaxEntries:     0,
				PositiveTtlMin: 60,
				PositiveTtlMax: 300,
				NegativeTtl:    30,
			},
			checks: []string{
				"max-cache-entries=0",
			},
		},
		{
			name: "NegativeTtl zero",
			cache: engine.CacheConfig{
				MaxEntries:     100000,
				PositiveTtlMin: 60,
				PositiveTtlMax: 300,
				NegativeTtl:    0,
			},
			checks: []string{
				"max-negative-ttl=0",
			},
		},
		{
			name: "PositiveTtlMin and PositiveTtlMax both zero",
			cache: engine.CacheConfig{
				MaxEntries:     100000,
				PositiveTtlMin: 0,
				PositiveTtlMax: 0,
				NegativeTtl:    30,
			},
			checks: []string{
				"minimum-ttl-override=0",
				"max-cache-ttl=0",
			},
		},
		{
			name: "very large MaxEntries",
			cache: engine.CacheConfig{
				MaxEntries:     10000000,
				PositiveTtlMin: 60,
				PositiveTtlMax: 300,
				NegativeTtl:    30,
			},
			checks: []string{
				"max-cache-entries=10000000",
			},
		},
	}

	renderer := &PowerDNSRenderer{}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			config := validPowerDNSConfig()
			config.Cache = tt.cache

			got, err := renderer.Render(config)
			if err != nil {
				t.Fatalf("Render() returned error: %v", err)
			}

			for _, check := range tt.checks {
				if !strings.Contains(got, check) {
					t.Fatalf("Render() output does not contain %q\nfull output:\n%s", check, got)
				}
			}
		})
	}
}

func TestPowerDNSRendererRejectsEncryptedTransports(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	config := validPowerDNSConfig()
	config.Upstreams = []engine.UpstreamConfig{{Address: "dns.google", Transport: engine.UpstreamTransportDoH}}

	if _, err := renderer.Render(config); err == nil {
		t.Fatal("expected error for encrypted upstream transport in PowerDNS renderer")
	}
}
