package powerdns

import (
	"strings"
	"testing"

	operatorconfig "github.com/astradns/astradns-operator/pkg/engineconfig"
	v1alpha1 "github.com/astradns/astradns-types/api/v1alpha1"
	"github.com/astradns/astradns-types/engine"
)

func TestPowerDNSRendererRenderFullConfig(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	config := &engine.EngineConfig{
		Upstreams: []engine.UpstreamConfig{
			{Address: "1.1.1.1", Port: 53},
			{Address: "8.8.8.8", Port: 5353},
		},
		Cache: engine.CacheConfig{
			MaxEntries:        4096,
			PositiveTtlMin:    30,
			PositiveTtlMax:    120,
			NegativeTtl:       20,
			PrefetchEnabled:   true,
			PrefetchThreshold: 7,
		},
		ListenAddr: "0.0.0.0",
		ListenPort: 5354,
	}

	got, err := renderer.Render(config)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	expected := `# PowerDNS Recursor configuration — generated by AstraDNS
local-address=0.0.0.0
local-port=5354
daemon=no
write-pid=no
disable-syslog=yes
log-common-errors=yes
threads=2
max-cache-entries=4096
max-negative-ttl=20
minimum-ttl-override=30
max-cache-ttl=120
forward-zones=.=1.1.1.1:53;8.8.8.8:5353
allow-from=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16`

	if strings.TrimSpace(got) != strings.TrimSpace(expected) {
		t.Fatalf("Render() output mismatch\nexpected:\n%s\n\ngot:\n%s", expected, got)
	}
}

func TestPowerDNSRendererRenderDefaults(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	config := &engine.EngineConfig{
		Upstreams: []engine.UpstreamConfig{{Address: "1.1.1.1", Port: 53}},
		Cache: engine.CacheConfig{
			MaxEntries:     100000,
			PositiveTtlMin: 60,
			PositiveTtlMax: 300,
			NegativeTtl:    30,
		},
		ListenAddr: "127.0.0.1",
		ListenPort: 5354,
	}

	got, err := renderer.Render(config)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	checks := []string{
		"local-address=127.0.0.1",
		"local-port=5354",
		"max-cache-entries=100000",
		"forward-zones=.=1.1.1.1:53",
	}

	for _, check := range checks {
		if !strings.Contains(got, check) {
			t.Fatalf("Render() output does not contain %q\nfull output:\n%s", check, got)
		}
	}
}

func TestPowerDNSRendererRoundTrip(t *testing.T) {
	t.Parallel()

	gen := &operatorconfig.DefaultConfigGenerator{}
	pool := &v1alpha1.DNSUpstreamPool{
		Spec: v1alpha1.DNSUpstreamPoolSpec{
			Upstreams: []v1alpha1.Upstream{
				{Address: "1.1.1.1"},
				{Address: "8.8.8.8", Port: 5353},
			},
		},
	}
	profile := &v1alpha1.DNSCacheProfile{
		Spec: v1alpha1.DNSCacheProfileSpec{
			MaxEntries: 2048,
			PositiveTtl: v1alpha1.TtlConfig{
				MinSeconds: 45,
				MaxSeconds: 180,
			},
			NegativeTtl: v1alpha1.NegTtlConfig{Seconds: 20},
			Prefetch:    v1alpha1.PrefetchConfig{Enabled: true, Threshold: 8},
		},
	}

	config, err := gen.Generate(pool, profile)
	if err != nil {
		t.Fatalf("Generate() returned error: %v", err)
	}

	renderer := &PowerDNSRenderer{}
	got, err := renderer.Render(config)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	expected := `# PowerDNS Recursor configuration — generated by AstraDNS
local-address=127.0.0.1
local-port=5354
daemon=no
write-pid=no
disable-syslog=yes
log-common-errors=yes
threads=2
max-cache-entries=2048
max-negative-ttl=20
minimum-ttl-override=45
max-cache-ttl=180
forward-zones=.=1.1.1.1:53;8.8.8.8:5353
allow-from=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16`

	if strings.TrimSpace(got) != strings.TrimSpace(expected) {
		t.Fatalf("round-trip output mismatch\nexpected:\n%s\n\ngot:\n%s", expected, got)
	}
}

func TestPowerDNSRendererMetadata(t *testing.T) {
	t.Parallel()

	renderer := &PowerDNSRenderer{}
	if renderer.EngineType() != engine.EnginePowerDNS {
		t.Fatalf("EngineType() = %q, want %q", renderer.EngineType(), engine.EnginePowerDNS)
	}
	if renderer.ConfigFileName() != "recursor.conf" {
		t.Fatalf("ConfigFileName() = %q, want %q", renderer.ConfigFileName(), "recursor.conf")
	}
}
