---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - dns.astradns.com
  resources:
  - dnscacheprofiles
  - dnsupstreampools
  - externaldnspolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.astradns.com
  resources:
  - dnscacheprofiles/status
  - dnsupstreampools/status
  - externaldnspolicies/status
  verbs:
  - get
  - patch
  - update
