apiVersion: v2
name: astradns
description: AstraDNS - Kubernetes DNS management operator and agent
type: application
version: 0.2.9
appVersion: "0.2.9"
home: https://docs.astradns.com/
sources:
  - https://github.com/astradns/astradns-operator
  - https://github.com/astradns/astradns-agent
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Homepage
      url: https://docs.astradns.com/
    - name: Source
      url: https://github.com/astradns/astradns-operator
    - name: Agent source
      url: https://github.com/astradns/astradns-agent
  artifacthub.io/images: |
    - name: astradns-operator
      image: ghcr.io/astradns/astradns-operator:v0.2.9
    - name: astradns-agent-unbound
      image: ghcr.io/astradns/astradns-agent:v0.2.9-unbound
    - name: astradns-agent-coredns
      image: ghcr.io/astradns/astradns-agent:v0.2.9-coredns
    - name: astradns-agent-powerdns
      image: ghcr.io/astradns/astradns-agent:v0.2.9-powerdns
    - name: astradns-agent-bind
      image: ghcr.io/astradns/astradns-agent:v0.2.9-bind
maintainers:
  - name: AstraDNS Team
keywords:
  - dns
  - kubernetes
  - operator
  - daemonset
  - coredns
  - unbound
  - powerdns
  - bind
  - dnscache
  - dns-security
  - observability
