{{- $profile := include "astradns.agent.topology.profile" . -}}
{{- if eq $profile "central" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "astradns.fullname" . }}-agent
  namespace: {{ include "astradns.namespace" . }}
  labels:
    {{- include "astradns.agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agent.deployment.replicas }}
  {{- with .Values.agent.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "astradns.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "astradns.agent.labels" . | nindent 8 }}
        {{- with .Values.agent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "astradns.agent.podSpec" . | nindent 6 }}
{{- end }}
