apiVersion: v1
kind: Service
metadata:
  name: {{ include "astradns.fullname" . }}-agent-metrics
  namespace: {{ include "astradns.namespace" . }}
  labels:
    {{- include "astradns.agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "astradns.agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 9153
      targetPort: metrics
      protocol: TCP
