apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.operator.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "astradns.fullname" . }}-operator
  namespace: {{ include "astradns.namespace" . }}
  labels:
    {{- include "astradns.operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
